packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  "@biomejs/biome": true
  "@swc/core": true
  sharp: true
  "@prisma/engines": true
  prisma: true
  cpu-features: false
  protobufjs: false
  ssh2: false
